package application.auth.roles;

/**
 * Created by gipai on 9/28/2017.
 */
public enum PermissionType {

    CREATE_COMPANY,
    DELETE_COMPANY,
    READ_COMPANY,
    UPDATE_COMPANY,

    CREATE_DEPARTMENT,
    DELETE_DEPARTMENT,
    READ_DEPARTMENT,
    UPDATE_DEPARTMENT,
    
    CREATE_CLIENT,
    DELETE_CLIENT,
    READ_CLIENT,
    UPDATE_CLIENT,
    
    CREATE_PHASE,
    DELETE_PHASE,
    READ_PHASE,
    UPDATE_PHASE,

    CREATE_USER,
    DELETE_USER,
    READ_USER,
    UPDATE_USER,

    CREATE_ROLE,
    DELETE_ROLE,
    READ_ROLE,
    UPDATE_ROLE,
    
    CREATE_PROJECT,
    DELETE_PROJECT,
    READ_PROJECT,
    UPDATE_PROJECT,
    
    CREATE_PRODUCT,
    DELETE_PRODUCT,
    READ_PRODUCT,
    UPDATE_PRODUCT,

    CREATE_CATEGORY,
    DELETE_CATEGORY,
    READ_CATEGORY,
    UPDATE_CATEGORY,
    
    CREATE_DOCUMENT,
    DELETE_DOCUMENT,
    READ_DOCUMENT,
    UPDATE_DOCUMENT,
	
    CREATE_SPECIFICATION,
    DELETE_SPECIFICATION,
    READ_SPECIFICATION,
    UPDATE_SPECIFICATION,
    
    CREATE_BOQ,
    DELETE_BOQ,
    READ_BOQ,
    UPDATE_BOQ,
    
    CREATE_BOQDEPARTMENT,
    DELETE_BOQDEPARTMENT,
    READ_BOQDEPARTMENT,
    UPDATE_BOQDEPARTMENT,
    
	CREATE_SECTION,
    DELETE_SECTION,
    READ_SECTION,
    UPDATE_SECTION,
    
    CREATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    READ_EMPLOYEE,
    UPDATE_EMPLOYEE,
    
    CREATE_MOM,
    DELETE_MOM,
    READ_MOM,
    UPDATE_MOM,
	
    CREATE_CR,
    DELETE_CR,
    READ_CR,
    UPDATE_CR;

}
